export { default as Home } from './home/Home'
export { default as NotFound } from './notFound/NotFound'
export { default as Layout } from './layout/Layout'
export { default as Header } from './header/Header'
export { default as ProjectList } from './projectList/ProjectList'
export { default as Slide } from './slide/Slide'
